lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        frequency_base: 5
        batch_frequency: 25
  modelcheckpoint_step:
    params:
      every_n_train_steps: 100
  trainer:
    max_steps: 400
    log_every_n_steps: 5
    accumulate_grad_batches: 4
    precision: 16
    distributed_backend: ddp
    gpus: 7,
